
package com.github.alejopj.ws.soap.helloworld.server.services.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.github.alejopj.ws.soap.helloworld.server.services.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "hello", targetNamespace = "")
    @RequestWrapper(localName = "sayHelloTo", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.SayHelloTo")
    @ResponseWrapper(localName = "sayHelloToResponse", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.SayHelloToResponse")
    @Action(input = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/sayHelloToRequest", output = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/sayHelloToResponse")
    public String sayHelloTo(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "hello", targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.SayHelloWorldResponse")
    @Action(input = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/sayHelloWorldRequest", output = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/sayHelloWorldResponse")
    public String sayHelloWorld();

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "thankYou", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.ThankYou")
    @ResponseWrapper(localName = "thankYouResponse", targetNamespace = "http://services.server.helloworld.soap.ws.alejopj.github.com/", className = "com.github.alejopj.ws.soap.helloworld.server.services.ThankYouResponse")
    @Action(input = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/thankYouRequest", output = "http://services.server.helloworld.soap.ws.alejopj.github.com/HelloWorldService/thankYouResponse")
    public void thankYou(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
